export default WORDS = [

    // PHRASAL VERBS
    // https://www.youtube.com/watch?v=kJ_R7cOqh5k&t=2154s
    { id: 1, word: "Speak up", translation: "Hablar alto", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Shut up", translation: "Callarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Come back", translation: "Regresar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Go away", translation: "Irse, Vete", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Put off", translation: "Posponer", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Carry out", translation: "Llevar a cabo", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Take over", translation: "Tomar el control", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Hand over", translation: "Entregar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Break up", translation: "Romperse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Make up", translation: "Reconciliarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Stand up", translation: "Ponerse de pie", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Sit down", translation: "Sentarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Wake up", translation: "Despertar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Fall asleep", translation: "Dormirse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Knock down", translation: "Derribar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Build up", translation: "Fortalecer", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Come in", translation: "Entrar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Go out", translation: "Salir", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Come up", translation: "Subir", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Go Down", translation: "Bajar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Drop off", translation: "Dejar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Pick up", translation: "Recoger", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Back up", translation: "Retroceder", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Move forward", translation: "Avanzar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Pull over", translation: "Orillarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Drive away", translation: "Alejarse conduciendo", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Take off", translation: "Quitar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Put on", translation: "Poner", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Pick up", translation: "Contestar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Hang up", translation: "Colgar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Slow down", translation: "Desacelerar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Speed up", translation: "Acelerar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Put together", translation: "Armar (Algo)", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Take apart", translation: "Desarmar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Give up", translation: "Rendirse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Keep on", translation: "Seguir", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Take out", translation: "Sacar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Put away", translation: "Guardar (Algo)", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Turn up", translation: "Subir", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Turn down", translation: "Bajar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Get on", translation: "Subir", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Get off", translation: "Bajarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Pick up", translation: "Recoger", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Drop off", translation: "Reco", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Stay in", translation: "Quedarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Chill out", translation: "Relajarte", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Stress out", translation: "Estresarte", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Check in", translation: "Registrarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Check out", translation: "Irse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Look up to", translation: "Admirar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Look down on", translation: "Despreciar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Tidy up", translation: "Ordenar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Mess up", translation: "Arruinar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Warm up", translation: "Calentarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Cold down", translation: "Enfriarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Take off", translation: "Despegar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Carry on", translation: "Seguir", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Calm down", translation: "Calmar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Ask about", translation: "Preguntar por", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Wake up", translation: "Reco", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Watch out", translation: "Cuidado!", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Break up", translation: "Romper", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Make (Something) up", translation: "Inventar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Work out", translation: "Hacer ejercicio", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Hurry up", translation: "Darse prisa!", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Hang out", translation: "Salir", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Get in", translation: "Subir", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Look after", translation: "Cuidar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Let (someone) down", translation: "Degraudar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Look for", translation: "Buscar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Try on", translation: "Probar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Find out", translation: "Averiguar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Call off", translation: "Cancelar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Do (Something) over", translation: "Hacer (algo) otra vez", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Figure (something) out", translation: "Averiguar (algo)", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Pass out", translation: "Desmayar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Put (something) off", translation: "Posponer", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Back (someone) up", translation: "Respaldar (a alguien)", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Break down", translation: "Averiar/Descomponer", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Check (something) out", translation: "Hechale un vistaso, Comprobar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Cheer (someone) up", translation: "Animar (a alguien)", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Dive into (something)", translation: "Sumergirse en (algo)", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Come across (someone)", translation: "Encontrarse (con)", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Pick out (something)", translation: "Elegir (algo)", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Put up with (something)", translation: "Soportar/Tolerar", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Butt in", translation: "Entrometerse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Chicken out", translation: "Acobardarse", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Come about", translation: "Suceder/ocurrir", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Mak", translation: "Reco", categories: ["PHRASAL VERBS"] },
    { id: 1, word: "Mak", translation: "Reco", categories: ["PHRASAL VERBS"] },



    //
    { id: 1, word: "After You", translation: "Después de ti", categories: ["Expressions"] },
    { id: 1, word: "Bless you", translation: "Salud", categories: ["Expressions"] },
    { id: 1, word: "Catch up", translation: "Alcánzame", categories: ["Expressions"] },
    { id: 1, word: "Come on", translation: "Vamos", categories: ["Expressions"] },
    { id: 1, word: "Hang on", translation: "Espera", categories: ["Expressions"] },
    { id: 1, word: "Hold on", translation: "Espera", categories: ["Expressions"] },
    { id: 1, word: "I gree", translation: "Estoy de acuerdo", categories: ["Expressions"] },
    { id: 1, word: "i'm sorry", translation: "Lo siento", categories: ["Expressions"] },
    { id: 1, word: "No way", translation: "De ninguna manera", categories: ["Expressions"] },
    { id: 1, word: "See you", translation: "Nos vemos", categories: ["Expressions"] },
    { id: 1, word: "So long", translation: "Hasta luego", categories: ["Expressions"] },
    { id: 1, word: "Take care", translation: "Cuídate", categories: ["Expressions"] },
    { id: 1, word: "Thank you", translation: "Gracias", categories: ["Expressions"] },
    { id: 1, word: "Time's up", translation: "Se acabó el tiempo", categories: ["Expressions"] },
    { id: 1, word: "Well done", translation: "Bien hecho", categories: ["Expressions"] },
    { id: 1, word: "Why not?", translation: "Por qué no?", categories: ["Expressions"] },
    
]